---
title: "Нефть после Дохи: восхождение или откат?"
date: 2016-04-25
author: "Марсель Салихов"
categories: ["нефть", "энергетика"]
description: "Провал переговоров в Дохе неделю назад сулил нерадостные перспективы для нефтяных цен. На протяжении последних месяцев именно переговорный процесс крупнейших"
---

Провал переговоров в Дохе неделю назад сулил нерадостные перспективы для нефтяных цен. На протяжении последних месяцев именно переговорный процесс крупнейших производителей нефти создавал информационный фон, который способствовал повышению цен. Хотя само соглашение о «заморозке» добычи на уровнях января 2016 года не могло повлиять непосредственно на текущий баланс на мировом рынке нефти, оно могло стать свидетельством возможности сотрудничества стран-производителей, чтобы воздействовать на мировой рынок. 

Однако Доха завершилась провалом. Стороны не только не смогли договориться об анонсированной ранее  «заморозке», но даже согласовать общее заявление.  В этом смысле провал был похож на декабрьскую встречу ОПЕК – тогда финальные переговоры также сильно затянулись, ни о чем договориться не удалось, а итоговая пресс-конференция произвела удручающее впечатление. После декабрьской встречи ОПЕК начался новый раунд снижения цен на нефть, в ходе которого цены упали более чем на 50%. Итоги Дохи вновь показали, что не-нефтяные интересы участников чересчур противоречат друг другу. Саудовская Аравия, поддержавшая ранее «заморозку» добычи, оказалась не готова присоединяться к соглашениям, которые создают какие-либо выгоды для Ирана. Политика оказалась важнее экономики. 

Абсолютное большинство аналитиков и экспертов предполагало, что провал в Дохе является сильным «медвежьим» сигналом для рынка, так как увеличивает вероятность сохранения ценовой войны между производителями и роста дисбаланса на рынке. Действительно при открытии торгов в понедельник, 18 апреля, нефтяные котировки снизились на 6-8% «на Дохе». Однако за последующие дни нефтяные цены более чем компенсировали провал этот  – за прошлую неделю котировки Brent выросли на 5%, WTI – почти на 9%. Новости о завершении забастовки работников нефтяной промышленности в Кувейте никак не повлияли на царящий, на рынке оптимизм. 

Важным вопросом с точки зрения понимания происходящего на рынке нефти представление о том, почему провал в Дохе привел к противоположному результату с точки зрения реакции нефтяных цен.  Здесь возможны два варианта. 

**Первый вариант**. Повышение цен на нефть в последние два месяца не было связано с Дохой, а просто совпало с ней во времени. Есть несколько факторов, которые также способствовали росту цен. Панический настрой финансовых рынков, который царил в январе-феврале, изменился на противоположный – сверхоптимистичный. Этому способствовало меры по дальнейшему ослаблению денежно-кредитной политики в развитых странах (отрицательные ставки в еврозоне и Японии), а также начало очередного раунда стимулирующей политики в Китае.  Скоординированные действия денежных властей смогли остановить панику. Поток экономической статистики последнего времени хотя и не дает оснований для большого оптимизма, указывает на что, что пугавшая всех рецессия в американской экономике в начале 2016 года не началась. В США сохраняется сильная динамика спроса на бензин при устойчивом снижении количества задействованных буровых установок (опережающий показатель будущей добычи). Это дает основания предполагать, что потребность американской экономики в импортной нефти будет увеличиваться и это позволит сократить профицит на мировом рынке. 

**Второй вариант**. Фактор Дохи отразится на нефтяных ценах после того, как будут понятны стратегии Саудовской Аравии и Ирана на рынке физической нефти.  Основной риск провала переговоров заключается в том, что на рынке начнется очередной раунд ценовой войны между основными производителями. Саудовская Аравия имеет возможности нарастить добычу с текущих уровней еще на 0,5-1,0 млн баррелей в сутки. Королевство к июню [планирует](http://www.bloomberg.com/news/articles/2016-04-24/aramco-said-to-expand-oilfield-in-may-to-maintain-saudi-capacity) завершить к июню расширение мощностей на месторождении и [начало](http://www.bloomberg.com/news/articles/2016-04-26/saudi-spot-crude-deal-in-china-seen-by-citi-as-dramatic-shift) осуществлять поставки на спотовом рынке.  Освободившийся от большей части наложенных на него санкций Иран продемонстрировал, что способен достаточно быстро восстанавливать «потерянную» добычу. В настоящее время также довольно большой объем незапланированного сокращения  добычи – аварии в Нигерии, Ираке, простой Кувейта. По данным Bloomberg, объем незапланированных перебоев в добыче на мировом рынке составляет около 2,5 млн баррелей в сутки. Однако, скорее всего, эти перебои носят временный характер и в ближайшие месяцы могут быть возобновлены. Если все эти производители увеличат добычу и начнут ценовую конкуренцию за спотовых покупателей на физическом рынке – это неизбежно отразится на ценах. 

Ситуация весны 2016 года опасным образом напоминает прошлый год. В первом полугодии так же  произошел значительный рост нефтяных цен, которые к маю 2015 года превышали $65/баррель и казалось, что худшее – уже позади. Однако опасения по поводу устойчивости китайской экономики, триггером для которых стала девальвация юаня, привели к провалу цен в августе 2015, а потом – в январе 2016.  Добыча в США оказалась гораздо более устойчивой к низким ценам, чем это прогнозировали сами американские власти в лице Управления по энергетической информации (EIA). ОПЕК снова показал неспособность повлиять на рынок и наращивал добычу. Результатом всего этого стали цены ниже $30 баррель – минимальные за последние 15 лет значения. 

Прогнозировать нефтяные цены – сложно, систематически точно – [невозможно](https://www.federalreserve.gov/pubs/ifdp/2011/1022/ifdp1022.pdf). Тем не менее, как  представляется, пресловутое «дно» на рынке уже пройдено. Потребуется новое сочетание нескольких сильных негативных шоков , чтобы «вернуть» цены ниже $30/баррель – к границе текущих операционных затрат правой части кривой себестоимости предложения на мировом рынке (добыча Северного моря, трудноизвлекаемая нефть и проч.). Причем в условиях сезонного роста во 2-3 кварталах это становится более сложным.

Однако фундаментальных факторов, которые обосновывали возможность дальнейшего существенного роста котировок тоже не просматривается. Риски ценовой войны между основными производителями остаются высокими. Запасы нефти в хранилищах все еще увеличиваются, хотя и более медленными темпами.  Способность центральных банков  неопределенно долго противостоять структурным экономическим изменениям, таким как замедление экономики Китая, также вызывает вопросы. 

  


Наиболее вероятным сценарием видится «плоский» рынок в ближайшие несколько месяцев. За это время прояснится, каковы стратегии Саудовской Аравии и Ирана на рынке физической нефти. Станет понятно ли обоснованы ли ожидания сильного сокращения добычи в США. После того, как рынок найдет ответы на эти вопросы, последует очередное сильное движение –  в одну из сторон.
