---
title: "Восемь лет без ОПЕК. Почему картель решил вернуться?"
date: 2016-12-01
author: "Марсель Салихов"
categories: ["нефть", "энергетика"]
description: "_статья для Republic_       Заседание ОПЕК 30 ноября 2016 года называли одним из важнейших для организации событий за десятилетия. Картель должен был"
---

_статья для Republic_

  
  
Заседание ОПЕК 30 ноября 2016 года называли одним из важнейших для организации событий за десятилетия. Картель должен был подтвердить необходимость своего существования или сдаться, расписавшись в собственной недееспособности.  
  
Ровно два года назад, в ноябре 2014 года, ОПЕК не стала сокращать квоты и фактически отказалась от попыток влиять на цену нефти. Это решение начало новый этап для мирового рынка – период самоустранения нефтяного картеля от своей основной функции. Тогда рынок потерял привычные ориентиры – в результате цены снизились c $75–80 за баррель в конце ноября 2014 года до $45–50 в январе 2015-го. Спустя год страны ОПЕК вновь подтвердили приверженность новой стратегии и отказались в принципе от формального механизма квотирования. Теперь каждая страна могла решать сама, сколько нефти добывать и почем ее продавать. Рынок, решивший, что ОПЕК теперь уже можно списывать со счетов, сделал свои выводы. Неверие в способность картеля стабилизировать мировой рынок стало одной из причин, почему цены на нефть в начале 2016 года опустились ниже $30 за баррель.  
Если подвести итоги этих двух лет, то несложно сделать вывод: новая политика ОПЕК приводила к последовательному снижению цен даже не потому, что страны-участники не могли сократить добычу, а потому, что они ее бурно наращивали. 

  


С конца 2014 года суммарная добыча стран ОПЕК выросла примерно на 2,5–3,0 млн баррелей в сутки – с 31 млн до 33,6–34,0 млн баррелей в октябре 2016 года. За то же время мировые цены на нефть упали почти в два раза. Парадокс заключается в том, что текущий дисбаланс на рынке, понимаемый как превышение текущего предложения над текущим спросом, оценивается американским Управлением энергетической информации (EIA) в 0,5–1,0 млн баррелей в сутки. Получается, что если бы ОПЕК сохранила добычу на уровне конца 2014 года, то мировой рынок нефти уже давно находился бы в дефиците и мы сейчас наблюдали бы другой уровень цен.

Основная предполагаемая мишень новой политики ОПЕК – американская нефтедобыча – при этом пострадала не так уж сильно и сократилась примерно на 1 млн баррелей в сутки. В остатке получается, что прирост добычи ОПЕК за последние два года (2,5–3,0 млн баррелей в день) более чем в два раза превысил сокращение добычи в США (1 млн баррелей в день). В результате новой политики предложение на мировом рынке выросло, а цены снизились.  
В полном соответствии с «дилеммой заключенного» из теории игр каждый производитель нефти, действуя из своих собственных интересов, всеми силами наращивал добычу, чтобы максимизировать свою выручку, и тем самым обрушивал цены, ухудшая свое положение.  
Однако в конце сентября 2016 года на неофициальной встрече ОПЕК в Алжире неожиданно для многих страны-участницы договорились о потенциальном сокращении добычи на 0,6–1,2 млн баррелей в сутки – впервые за восемь лет. Однако распределение квот по странам не было установлено – достичь договоренностей планировали как раз к заседанию 30 ноября.  
Важнейшей причиной, почему встреча в Алжире принесла хоть какие-то результаты, стало изменение позиций Саудовской Аравии. Если раньше Саудовская Аравия как крупнейший производитель и неофициальный лидер картеля придерживалась мнения «давайте дадим рынку самому устанавливать справедливый уровень цен, а неэффективные производители пусть уходят с рынка», то теперь эта позиция изменилась. Саудовская Аравия в лице нового министра энергетики Халида аль-Фалиха дала понять, что в принципе договоренность о сокращении добычи возможна. Королевство не будет выступать против при одном условии – все участники должны внести свой посильный вклад в общее дело.

  
На мой взгляд, смена позиции Саудовской Аравии была связана в первую очередь с нарастающими проблемами в экономике страны на фоне низких цен на нефть. К примеру, в 2015 году дефицит государственного бюджета Саудовской Аравии достиг 15% ВВП. Несмотря на бюджетную консолидацию, в 2016 году дефицит составит 10–12% ВВП. Такой уровень дефицита не является устойчивым даже на горизонте пяти лет. Королевству требовалось либо резко сократить уровень госрасходов, в первую очередь за счет сокращения занятости (60–80% занятости в стране приходится на бюджетный сектор), либо девальвировать фиксированный к доллару США реал. Оба варианты чреваты непредсказуемыми социально-политическими последствиями. Поэтому оставался другой путь – повысить нефтяные доходы.  
  
Свою роль в изменении позиции Саудовской Аравии сыграло и то, что сейчас в принципе благоприятное время для подобной договоренности – мировой рынок нефти постепенно балансируется, рост запасов замедлился, опасения по поводу замедления мировой экономики уменьшились.  
Однако формализация алжирского соглашения давалась с большим трудом. В последние два месяца даже привычно волатильный нефтяной рынок лихорадило больше обычного. Настроения еженедельно менялись из крайности в крайность – от «растущего оптимизма» по поводу будущей договоренности до полного неверия рынка в способность ОПЕК договориться о чем-либо вообще, и обратно. Как обычно, страсти подогревали противоречащие друг другу заявления министров, утечки информации из анонимных источников и какофония всевозможных аналитических мнений. Стабильности не добавило то, что отдельные страны перед встречей решили по максимуму нарастить собственную добычу, с тем чтобы усилить переговорную позицию и договариваться о сокращении с более высокой базы.  
Еще 29 ноября, накануне заседания, консенсус рынка заключался в том, что сделки не будет. Однако, как это ни удивительно, ОПЕК все же смогла извлечь уроки из опыта предыдущих двух лет и договорилась о сокращении добычи на 1,2 млн баррелей в сутки. Обязательства вступают в силу с января 2017 года. Утвержденные сейчас 1,2 млн баррелей в день – это верхняя граница сентябрьских договоренностей, то есть максимум, на что можно было рассчитывать. Еще до итоговой пресс-конференции заседания цены на нефть выросли примерно на 8% – на $4 за баррель. Таковой оказалась цена способности участников договориться.

  
ОПЕК выучила еще один важный урок – для воздействия на рынок надо уметь превышать его ожидания. Таким «превышением» стали новости о координации ОПЕК с другими крупными производителями. Как было заявлено на итоговой пресс-конференции, страны, не входящие в ОПЕК, взяли обязательство дополнительно сократить добычу на 600 тысяч баррелей в сутки. Россия [обещала](https://republic.ru/posts/76842) сократить добычу на 300 тысяч баррелей в сутки (в октябре добыча нефти в стране обновила постсоветский рекорд и составила 11,2 млн баррелей в сутки). Эта информация не учитывалась в ценах и стала неожиданной для рынка. Члены ОПЕК также попытались развеять опасения по поводу собственной низкой дисциплинированности и договорились о создании специального комитета, который будет мониторить соблюдение обязательств. Разумеется, долгосрочность текущего скачка нефтяных цен будет зависеть от того, насколько достигнутые договоренности будут фактически соблюдаться. Однако это первый шаг к восстановлению контроля над рынком.  
  
30 ноября ОПЕК смогла доказать, что слухи о смерти картеля все же преувеличены. С другой стороны, это решение указывает на то, что политика последних двух лет была ошибочной. И ОПЕК наконец признала это.
