---
title: "Почему нам кажется, что цены растут быстрее инфляции?"
date: 2017-03-03
author: "Марсель Салихов"
categories: ["инфляция", "макроэкономика"]
description: "Росстат утверждает(http://www.gks.ru/bgd/free/b04_03/IssWWW.exe/Stg/d01/23.htm): за последний год цены в России в среднем выросли на 5% - на столько они"
---

Росстат [утверждает](http://www.gks.ru/bgd/free/b04_03/IssWWW.exe/Stg/d01/23.htm): за последний год цены в России в среднем выросли на 5% - на столько они оказались выше в январе 2017 года по сравнению с январем 2016-м. Похоже ли это на правду? Большинство россиян уверены, что нет. Данные ежемесячных [опросов](https://www.cbr.ru/DKP/?PrtId=infl) населения, проводимых по заказу Банка России, показывают, что «средний» россиянин систематически оценивает инфляцию в несколько раз выше. В том же январе 2017 года медианное значение инфляции по данным опроса - 14%. То есть половина опрошенных считают, что за последний год потребительские цены выросли больше, чем на 14%. В отдельные периоды этот разрыв становится еще заметнее. К примеру, в середине 2015 года почти 18% опрошенных предполагали, что цен за год выросли более чем на 50%, хотя официальная инфляция в этот периода составляла 15-16%.

Означает ли это, что Росстат измеряет совсем не ту инфляцию, которая актуальна для населения - что его методики неадекватны, а результаты бессмысленны? А ведь именно на этот показатель инфляции ориентируется вся политика Центробанка, ставя в прямую зависимость от него важнейший для экономики параметр ключевой ставки.

###  Показатели инфляции по Росстату (ИПЦ) и по опросам населения (медианное значение)

_Источник: Банк России, Росстат_  


###  **Откуда нестыковки?**

Причины такого расхождения росстатовского ИПЦ с впечатлениями людей об инфляции в магазинах условно можно разделить на три. Первая версия: Росстат лжет, «рисует» нужные цифры или намеренно использует неверные модели расчета в угоду финансовым властям. Это популярная точка зрения среди непрофессионалов. Но эту версию можно сразу отбросить: росстатовские [методики](http://www.gks.ru/bgd/free/meta_2010/IssWWW.exe/Stg/2015/met-734.docx) расчета инфляции соответствуют очень подробным инструкциям Международного валютного фонда ([руководству](https://www.imf.org/external/pubs/ft/cpi/manual/2004/rus/cpi_ru.pdf) из 700 с лишним страниц). [Попытки](https://openeconomy.media/%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%B2%D0%BB%D0%B0%D1%81%D1%82%D0%B8-%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D1%8F%D1%82-%D0%BE-%D0%BC%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9-%D0%B8%D0%BD%D1%84%D0%BB%D1%8F%D1%86%D0%B8%D0%B8-%D0%BD%D0%BE-%D0%B2-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%D0%B0%D1%85-%D0%BC%D1%8B-%D0%B2%D0%B8%D0%B4%D0%B8%D0%BC-%D1%81%D0%BE%D0%B2%D1%81%D0%B5%D0%BC-%D0%B4%D1%80%D1%83%D0%B3%D0%BE%D0%B5-83c2dcb3c415#.empu1etqx) обнаружить в росстатовской модели серьезные искажения, как правило, сами грешат непониманием ее принципов. А первичная база данных, на основе которых Росстат определяет составляющие потребительской корзины, в анонимизированном виде [выложена](http://obdx.gks.ru/) в общий доступ - так что каждый желающий может проверить точность расчетов.

Вторая причина - несовершенство самой идеи вместить в одну цифру информацию об изменении цен на все категории товаров и услуг, потребляемых всеми социальными слоями. По этой причине профессиональное сообщество нередко критикует власти, когда они трактуют низкую  инфляцию как рост всеобщего благосостояния населения. Итоговые 5% не означают, что все цены в магазинах изменились на 5% плюс-минус какую-то небольшую погрешность. Напротив - это средняя температура между подорожавшими и подешевевшими товарами, часть из которых для каждой конкретной семьи совершенно не актуальны. 

Росстат, согласно международным рекомендациям, старается постоянно актуализировать набор товаров и услуг, попадающих в расчет. Это делается на основе данных о реальном потреблении 50 с лишним тысяч домохозяйств. В 2017 году в корзину ИПЦ входит 510 наименований, где самый дорогой товар - «Легковой автомобиль импортный новый» (1,13 млн рублей за штуку в январе 2017 года), а самый дешевый  – «Предоставление местного телефонного соединения при повременной системе оплаты услуг связи» (0,53 рубля за минуту). В этом году из списка убрали такие категории как «Отправка телеграммы обыкновенной внутренней, 15 слов», «Пошив женского платья», «Молоко сухое цельное», «Платок носовой», «Проигрыватель DVD» И добавили, среди прочего, «Поездку в Таиланд» и «Дополнительные занятия для детей дошкольного возраста». 

В соответствии с этим списком сотрудники ведомства с 20 по 25 числа каждого месяца фиксируют цены на товары и услуги в примерно 50 тысячах «точек сбора первичный ценовой информации» и собирают свыше полумиллиона ценовых котировок. Вклад каждого товара и услуги в общий показатель при сведении всех цен воедино определяется тоже по данным о реальных расходах панели российских домохозяйств. 

На этом возможности Росстата по актуализации корзины заканчиваются - общая цифра все равно будет отражать лишь среднюю температуру по больнице. Чтобы пятипроцентная инфляция в январе 2017-го была релевантна для вас, вы должны иметь доход в 24 тысяч рублей в месяц, тратить 38,1% денег на продовольственные товары, 35,7% – на непродовольственные, 26,3% – на услуги. Скорее всего, это не так. Если вы подписаны на Republic, вы уже выпадаете из «средней» модели, потому что средняя величина расходов «среднего домохозяйства» на СМИ в 2016 году - это 0,3% корзины ИПЦ или около тысячи рублей за весь год.

  


###  **Искажения восприятия**

Третья группа причин несовпадения официальной инфляции с нашими представлениями о ней - это наша склонность придавать большее значение отдельным деталям картины, не видя ее в целостности.

Во-первых, здесь работает** __ эффект замещения**. Если за год цены на говядину выросли на 25%, а на курицу – лишь на 10%, часть потребителей начинают чаще покупать курицу и реже говядину. Вместе с этим корректируется и корзина Росстата, ведь он даже не пытается оценивать наши упущенные возможности, он берет в расчет только то, что мы действительно покупаем. В итоге потребитель будет считать инфляцией в первую очередь сильный скачок цен на говядину, а Росстат его практически [не учтет](https://www.blogger.com/null)[[СМ1]](file:///G:/Dropbox/%D0%9F%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D0%B8/Republic_%D0%B8%D0%BD%D1%84%D0%BB%D1%8F%D1%86%D0%B8%D1%8F%2003-03-2017+%D1%81%D0%BC.docx#_msocom_1) . ****

Во-вторых, для людей не так принципиальна разница между **уровнем цен и изменением цен**. Мы склонны оценивать инфляцию не саму по себе, а в соотношении с изменением наших доходов, Росстат же этот фактор не учитывает. Даже при небольшой инфляции, но при не-растущих доходах потребители чувствуют себя угнетенно и винят во всем высокую инфляцию.  В 2015-2016 годах эффект инфляционного скачка в России воспринимался более болезненно в том числе и из-за стагнации номинальных доходов.   

В-третьих, мы не способны на повседневном уровне отдавать себе отчет, **сколько и на что мы тратим**. Исследования психологов и экономистов, занимающихся потребительским поведением, показывают, что в оценке инфляции мы ориентируемся на простые индикаторы, не отражающие весь наш потребительский набор. Если мы каждую неделю покупаем хлеб или молоко и заправляемся на АЗС, то именно эти товары и [формируют](http://openaccess.city.ac.uk/3509/1/EER-D-12-00388R2.pdf) наше индивидуальное восприятие инфляции, даже если они составляют небольшую часть нашей потребительской корзины. А бытовая техника или мебель, которые покупаются редко и вносят большой вклад в траты, имеют гораздо меньше шансов повлиять на наше восприятие. В 2015 году продовольственные товары в России дорожали сильно быстрее, чем непродовольственные товары и услуги, и в итоге рост цен психологически казался больше, чем он был на самом деле. 

####  **Индекс потребительских цен (ИПЦ) – основные составляющие**

**  
**

_Источник:   Росстат_


В-четвертых, доказано, что мы обращаем больше внимания на рост цен, чем на их снижение. Это связано с присущим большинству людей **«неприятием убытков»** (loss aversion). Многочисленные [исследования](http://www.jstor.org/stable/1942711?seq=1#page_scan_tab_contents) показывают, что люди воспринимают потерю 1 рубля острее, чем радуются выигрышу того же рубля. По тому же принципу мы ужасаемся ценам на гречку, выросшим в 2,5 раза за последние три года, но не обращаем внимания на цены на лук и свеклу, которые почти не изменились за это время, на то, что аренда квартир подешевела, а наш домашний интернет за это время стал быстрее в три раза  и на 20% дешевле.

Сторонникам теории «они нас обманывают» стоит знать, что феномен широкого недоверия к публикуемым официальным оценкам инфляции совсем не специфичен для России. В США вопрос корректного расчета инфляции в свое время был предметом специального расследования Сената и до сих пор остается мишенью ожесточенных политических дебатов. Причем одни аргументированно настаивают на том, что методика ИПЦ Bureau of Labor Statistics США занижает уровень «истинной» инфляции, а другие - что занижает. А согласно недавнему [исследованию](https://ec.europa.eu/info/publications/eu-consumers-quantitative-inflation-perceptions-and-expectations-evaluation_en) Европейской Комиссии, в Европе потребители считают, что инфляция в 2004-2015 годах была в 4 раза выше, чем официальный ИПЦ, рассчитываемый Евростатом. 

Поэтому вопрос, как правильно рассчитывать инфляцию, будет вечным. Но главное при этом, чтобы обе стороны - и потребители, и экономически власти - сознавали ограниченность любых таких расчетов и не пытались выдать частное за всеобщее, а желаемое за действительное.

  


  
  


  


[](https://www.blogger.com/null)
