---
title: "Почему BEER - это не про пиво, а про 'справедливый' курс валюты"
date: 2018-01-25
author: "Марсель Салихов"
categories: ["курс", "макроэкономика", "рубль"]
description: "Курс валюты и что с ним будет - один из немногих макроэкономических вопросов, которые волнуют практического каждого. 'Что будет с рублем? Брать ли доллар"
---

Курс валюты и что с ним будет - один из немногих макроэкономических вопросов, которые волнуют практического каждого. "Что будет с рублем? Брать ли доллар сейчас или подождать пару месяцев" — все, наверняка, сталкивались, с подобными вопросами и размышляли по этому поводу. Это сложные вопросы - и как с ценами на нефть, курс также довольно сложно прогнозировать. Но можно делать это лучше, чем просто рандом.

Специально для вас мы опубликовали количественную модель, которая позволит облегчить размышления по этому поводу. Модель называется BEER - от Behavioral Equilibrium Exchange Rate. По сути это модель оценки равновесного курса рубля. О чем вообще идет речь?

Как вы знаете, на изменение курса валюты одновременно оказывает множества факторов. Некоторые из них имеют фундаментальный макроэкономический характер - к примеру, изменение спроса на на товары экспорта/импорта, изменение экспортных/импортных цен, разница в инфляции и процентных ставках. Другие факторы - разовые или не-экономические - приводят к временным отклонениям курса от "справедливого" уровня. Современные методы количественного анализа позволяют оценивать обменный курс, не подверженный этим временным факторам.

  


Равновесный курс - это такое значение курса, при котором счета текущих операций и операций с капиталом и финансовыми инструментами платежного баланса находятся на долгосрочных/среднесрочных устойчивых уровнях. Таким образом, мы оцениваем валютный курс, к которому должен стремиться наблюдаемый рыночный курс в отсутствии краткосрочных шоков спроса/предложения валюты. Модель основана на работе _  Clark, MacDonald (2000, IMF); Filtering the BEER: A Permanent and Transitory Decomposition_, адаптированной для работы с месячными данными. Таким образом, в каждом месяце мы можем оценить, на сколько недооценен/переоценен по отношению к равновесному курсу (BEER). Соответственно, если рубль переоценен (то есть текущее значение выше, чем равновесный уровень), то можно ожидать, что на горизонте 6-9 месяцев рубль будет ослабляться (при аналогичных внешних условиях). И наоборот, если рубль недооценен - то можно ожидать укрепления рубля. Мы провели бектест за последние несколько лет и убедились, что модель имеет неплохую прогностическую силу.

Сейчас расчеты обновлены по декабрь 2017 года, когда среднемесячный курс доллара был около 59 рублей, а оценка равновесного курса - 58 рублей. Какого либо существенного отклонения рыночного курса от равновесного не было. В начале 2016 года совсем другая ситуация.

Сама модель доступна по адресу: [http://models.fief.ru/shiny/beer/](https://vk.com/away.php?to=http%3A%2F%2Fmodels.fief.ru%2Fshiny%2Fbeer%2F&cc_key= "http://models.fief.ru/shiny/beer/")

Напишите, если возникнут вопросы или комментарии. Как обычно, все данные оценок можно экспортировать в форматах xls/csv для собственного потребления. Все интерактивные графики можно сохранять в виде картинок png/jpeg/pdf.
