---
title: "Интерактивная карта результатов выборов мэра г. Москвы (8 сентября 2013 года) по отдельным УИКам"
date: 2013-09-11
author: "Марсель Салихов"
categories: ["R", "Москва", "выборы", "не-экономика", "обработка данных"]
description: "Как вы знаете, 8 сентября состоялись выбора мэра г. Москвы.  Уже довольно много материалов в Сети посвящено статистическому и географическому анализу этих"
---

Как вы знаете, 8 сентября состоялись выбора мэра г. Москвы.  Уже довольно много материалов в Сети посвящено статистическому и географическому анализу этих выборов на основе официальных [данных](http://www.moscow_city.vybory.izbirkom.ru/region/moscow_city?action=show&vrn=27720001368289&region=77&prver=0&pronetvd=null) Мосгоризбиркома.  
  
Я тоже решил посмотреть на эти данные и для начала построить карту с их визуализацией. Карт с результатами выборов в Сети уже довольно много. К примеру, на глаза попала [карта](http://www.kommersant.ru/doc/2259665) Коммерсанта, которая показывает данные по отдельным округам. Есть подобные карты по отдельным районам.  
  
  
  
  
Мне показалось интересным посмотреть на результаты голосований именно по отдельным УИКам на самом дробном уровне имеющейся детализации. В контексте появляющихся новостей о популярности С. Собянина в избирательных участках на территориях психбольниц это, наверно. имеет смысл. Также эту карту можно использовать, чтобы посмотреть на результаты голосований на вашем и соседних участках.  
Вот так выглядит итоговый вариант карты. Кружочками на карта выделены отдельные УИК - всего их 3365. Цвет кружочка синий, если на нем победил Собянин, и красный - если победил Навальный. Карта интерактивная, поэтому можно удалять-приближать и перемещать ее центр. Если навести мышкой на кружок, то появляется всплывающее окно, которое показывает номер УИК, его адрес и что это за объект (если есть такие данные), а также процентные результаты кандидатов. Как и говорил, можно проверить, как голосовал "свой" УИК.  
  
**Интерактивная карта результатов выборов мэра г. Москвы (8 сентября 2013 года) по отдельным УИКам**  
  
  
Что можно сказать по этой карте? Собянин победил на 3240 УИКах (это 96% от их общего числа), Навальный - на 123 (около 3,6%). Остальные кандидаты не смогли набрать большинства.  Карта дает возможность посмотреть именно на географическое распределение популярности. Можно выделить три "кластера", на которых смог получить большинство Навальный:  
  


  1. В пределах Садового кольца. Видно, что у Навального максимальная поддержка оказалась среди наиболее состоятельных слоев, живущих в самом центре города. 
  2. На севере - в районах Сокол, Аэропорт, Полежаевская. 
  3. На юге-западе в районах Ломоновский и Академический. 


  


Вот данные, которые я обработал для того, чтобы построить эту карту. Желающие могут скачать их и самостоятельно с ними поиграться. Вот [ссылка ](https://www.google.com/fusiontables/DataSource?docid=1rzXosrRsjAVxoH6jMCA9vjcYXvdONU1HNVAt2vw)на данные для скачивания из Google Fusion Tables.  
  


  
  
Максимальный результат Навального на УИК №202 (Кочновский проезд, 4, корп 1) - почти 63%.  
Собянин получил же максимальные 98,46% (!!!) на УИК №335 (Талдомская улица, д 6) - [судя ](http://xn--25-vlctj.xn--p1ai/)по всему, это государственное бюджетное учреждение "Психоневрологический диспансер №25". Интересная метафора, которую уже много где обсудили. На втором месте с результатом 88,15% за Собянина УИК №388 (Правобережная улица, д 4), в котором находится "Пансионат №1 для ветеранов войны и труда". Правда, больше УИКом с результатам больше 70% за Собянина нет.  
Наверно, еще много чего можно найти по данным - напишите, если что удалось обнаружить. Максимальный результат "за" Мельникова (18,24%) на УИК №61.  
  
Теперь вкратце об исходных данных для карты и как она была сделана.  
Исходные данные по результатам голосований получены из ["Сводной таблицы предварительных итогов голосований"](http://www.moscow_city.vybory.izbirkom.ru/region/region/moscow_city?action=show&root=1&tvd=27720001368293&vrn=27720001368289&region=77&global=&sub_region=77&prver=0&pronetvd=null&vibid=27720001368293&type=222) Московской городской избирательной комиссии. Они там выложены в не очень удобном виде (сначала по районам, а потом уже - по УИКам). Поэтому был написан скрипт на R, который скачивает и перерабатывает данные. Для карты я использовал только процентные итоги голосовать, хотя можно визуализировать и любые другие показатели, которые есть в исходных таблицах.  
Географические расположение УИКов [взята ](http://gis-lab.info/data/uik_geo/mgik_uiks_all_20130826.zip)с замечательного [gis-lab.ru](http://gis-lab.ru/)

Для создания непосредственно карты использовался отличный пакет [rCharts](https://github.com/ramnathv/rCharts), который позволяет обращаться к картографическому сервису [Leaflet JS](http://leafletjs.com/) и строить интерактивные карты непосредственно в R. Пакет еще в стадии разработки, поэтому я переработал готовый [пример](http://ramnathv.github.io/bikeshare/) от автора rCharts.
